MODEL:
  META_ARCHITECTURE: "OWTMASK"
#   WEIGHTS: "pretrained/R-50.pkl"
#   WEIGHTS: 'output/model_0004999.pth'
#   WEIGHTS: 'pretrained/model_final_9243eb.pkl'
#   WEIGHTS: 'output/model_0022499.pth'
#   WEIGHTS: 'OWTMASK_maskrcnn_finetune_agn_cls_4ep/model_0129999.pth'
#   WEIGHTS: 'OWTMASK_maskrcnn_finetune_agn_cls_debug/model_0019999.pth'
#   WEIGHTS: 'OWTMASK_maskrcnn_finetune_agn_cls_new_reid_loss/model_final.pth'
  WEIGHTS: 'OWTMASK_maskrcnn_finetune_80cls_new_reid_loss/model_final.pth'
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  OWTMASK:
    BATCH_INFER_LEN: 10

  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "ReidRes5ROIHeads"
    NUM_CLASSES: 80
    USE_DEFORMABLE_REID_HEAD: False

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0002
  STEPS: (81625,122437)
  MAX_ITER: 163250
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 10000
INPUT:
#   MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)  # [TODO] ori maskrcnn
  SAMPLING_FRAME_NUM: 2
  # MIN_SIZE_TRAIN_SAMPLING : ["range", "choice", "range_by_clip", "choice_by_clip"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  # RANDOM_FLIP : ["none", "horizontal", "flip_by_clip"]. "horizontal" is set by default.
  # RANDOM_FLIP: "flip_by_clip"
  # AUGMENTATIONS: []
  MIN_SIZE_TRAIN: (320, 352, 392, 416, 448, 480, 512, 544, 576, 608, 640)
  MIN_SIZE_TEST: 640
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
  COCO_PRETRAIN: True  # [TODO] 测试视频数据的时候改成false
  PRETRAIN_SAME_CROP: False   #if perform the same aug on key & reference frames
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
OUTPUT_DIR: OWTMASK_maskrcnn_finetune_80cls_new_reid_loss
TEST:
  DETECTIONS_PER_IMAGE: 1000
VERSION: 2

  
