MODEL:
  META_ARCHITECTURE: "OWTMASK"
#   WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS: 'pretrained/model_final_f96b26.pkl'
  MASK_ON: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN"  # BN
    # NORM: "BN"
    STRIDE_IN_1X1: True
  FPN:
    NORM: "SyncBN"  # 对齐
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
    CONV_DIMS: [-1, -1]  # LSJ
  ROI_HEADS:
    NAME: "ReidStandardROIHeads"
    # NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 80
    USE_DEFORMABLE_REID_HEAD: False
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 1  # [LSJ] 只有一层
    POOLER_RESOLUTION: 7
    NORM: naiveSyncBN_N  # LSJ
    CONV_DIM: 256  # LSJ
    NUM_CONV: 4  # LSJ
    FC_DIM: 1024  # LSJ
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    NORM: "BN"  # LSJ 猜的，但是权重完全加载了

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0002
  STEPS: (81625,122437)
  MAX_ITER: 163250
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 20000
INPUT:
#   MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)  # [TODO] ori maskrcnn
  SAMPLING_FRAME_NUM: 2
  # MIN_SIZE_TRAIN_SAMPLING : ["range", "choice", "range_by_clip", "choice_by_clip"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  # RANDOM_FLIP : ["none", "horizontal", "flip_by_clip"]. "horizontal" is set by default.
  # RANDOM_FLIP: "flip_by_clip"
  # AUGMENTATIONS: []
  MIN_SIZE_TRAIN: (320, 352, 392, 416, 448, 480, 512, 544, 576, 608, 640)
  MIN_SIZE_TEST: 640
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
  COCO_PRETRAIN: True  # [TODO] 测试视频数据的时候改成false
  PRETRAIN_SAME_CROP: False   #if perform the same aug on key & reference frames
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
OUTPUT_DIR: OWTMASK_R101_LSJ_OWT_CLS80
TEST:
  DETECTIONS_PER_IMAGE: 1000
VERSION: 2
