MODEL:
  META_ARCHITECTURE: "OWTMASK"
#   WEIGHTS: "pretrained/R-50.pkl"
#   WEIGHTS: 'output/model_0004999.pth'
#   WEIGHTS: 'pretrained/model_final_9243eb.pkl'
#   WEIGHTS: 'output/model_0022499.pth'
#   WEIGHTS: 'OWTMASK_maskrcnn_finetune_agn_cls_4ep/model_0129999.pth'
  WEIGHTS: 'OWTMASK_maskrcnn_finetune_agn_cls_new_reid_loss/model_final.pth'
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  OWTMASK:
    BATCH_INFER_LEN: 10
    INFERENCE_SELECT_THRES: 0.0

  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000  # [TODO] 1000改成300这样不用做任何后续过滤 对齐 IDOL  这里实际因为rpn的nms过滤可能不足1k个框
  ROI_HEADS:
    NAME: "ReidRes5ROIHeads"
    NUM_CLASSES: 1
  
DATASETS:
  TRAIN: ("ytvis_tao_train",)
  TEST: ("ytvis_tao_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0002
  STEPS: (81625,122437)
  MAX_ITER: 163250
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 2500
INPUT:
  SAMPLING_FRAME_NUM: 2  # 这个之前不知道为啥被注释了
  SAMPLING_FRAME_RANGE:  10
  # MIN_SIZE_TRAIN_SAMPLING : ["range", "choice", "range_by_clip", "choice_by_clip"]
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  # RANDOM_FLIP : ["none", "horizontal", "flip_by_clip"]. "horizontal" is set by default.
  RANDOM_FLIP: "flip_by_clip"
  # AUGMENTATIONS: []
  # MIN_SIZE_TRAIN: (360, 480)
  MIN_SIZE_TRAIN: (320, 352, 392, 416, 448, 480, 512, 544, 576, 608, 640)
  MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 480
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
  COCO_PRETRAIN: False  # [TODO] 测试视频数据的时候改成false
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False  # 这个之前也是True
  NUM_WORKERS: 8

TEST:
  DETECTIONS_PER_IMAGE: 1000
# OUTPUT_DIR: TEST_rpn1k_ytb_inference_new_reid_boxnms0.25_select0.0_addnew0.0_init0.0_nonfilter
OUTPUT_DIR: TEST_rpn1k_ytb_inference_prop_save
VERSION: 2

  
